/*!
 * Copyright (C) tkornuta, IBM Corporation 2015-2019
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __DEFS_H__
#define __DEFS_H__

namespace mic {
namespace htm {

// spatial pooler + temporal pooler
#define SYNAPSE_MINIMUM_PERMANENCE 0.001f
#define SYNAPSE_INITIAL_PERMANENCE 0.5f
#define SYNAPSE_CONNECTED_PERMANENCE 0.5f					// SYNAPSE CONNECTIVITY THRESHOLD
#define SM_SYNAPSE_PERMANENCE_DECREMENT 0.000f				// SYNAPSE PENALTY FOR NOT MATCHING THE INPUT
#define SM_SYNAPSE_PERMANENCE_INCREMENT 0.01f				// SYNAPSE REWARD FOR MATCHING THE INPUT
#define SM_SYNAPSE_PERMANENCE_RANGE_MIN 0.0f
#define SM_SYNAPSE_PERMANENCE_RANGE_MAX 1.0f

// spatial pooler defaults
#define DEFAULT_SP_SYNAPSE_PERMANENCE_DECREMENT 0.001f				// SYNAPSE PENALTY FOR NOT MATCHING THE INPUT
#define DEFAULT_SP_SYNAPSE_PERMANENCE_INCREMENT 0.001f				// SYNAPSE REWARD FOR MATCHING THE INPUT
#define DEFAULT_SP_PROXIMAL_SYNAPSES_PER_COLUMN 1024		// NUMBER, NO OF CONNECTIONS TO THE INPUT VECTOR
#define DEFAULT_SP_COLUMNS 1024										// NUMBER OF COLUMNS IN SPATIAL POOLER
#define DEFAULT_SP_INITIAL_COLUMN_BOOST	1.0f						// INITIAL BOOST VALUE
#define DEFAULT_SP_INITIAL_ACTIVE_DUTY_CYCLE 0.05f
#define DEFAULT_SP_INITIAL_MIN_DUTY_CYCLE 0.05f
#define DEFAULT_SP_INITIAL_OVERLAP_DUTY_CYCLE 0.05f
#define DEFAULT_SP_MIN_OVERLAP 0.0f									// MINIMUM OVERLAP THRESHOLD
#define DEFAULT_SP_LOCAL_INHIBITION_RADIUS 20						// Phase 2: Inhibition
#define DEFAULT_SP_MAX_COLUMNS 5	
#define DEFAULT_SP_MAX_DUTY_CYCLE_RADIUS 1
#define DEFAULT_SP_DUTY_CYCLE_HISTORY_WEIGHT 0.99f					// USED TO CALCULATE THE MOVING AVERAGE
#define DEFAULT_SP_BOOST_STEP 0.01f

// sequence memory
#define SM_CELLS_PER_COLUMN 4								// NUMBER OF CELLS IN A COLUMN
#define SM_SEGMENT_POTENTIAL_POOL 16						// NUMBER OF SYNAPSES PER SEGMENT
#define SM_SEGMENTS_PER_CELL 4								// MAX NUMBER OF SEGMENTS PER CELL
#define SM_SEGMENT_ACTIVATION_THRESHOLD 4					// NUMBER OF ACTIVE SYNAPSES NEEDED TO ACTIVATE A SEGMENT
#define SM_SEGMENT_MINIMUM_THRESHOLD 1
#define SM_SEGMENT_NEW_SYNAPSE_COUNT 4
#define SM_PERMANENCE_DECAY_RATE 0.05
#define SM_SYNAPSE_LEARNING_CACHE_MAX_SIZE 16384			// MAXIMUM NUMBER OF SYNAPSES CONNECTED TO LEARNING CELLS STORED IN MEMORY

//input
#define DEFAULT_SP_INPUT_VECTOR_LENGTH 1024

} /* namespace htm */
} /* namespace mic */

#endif
