MachineIntelligenceCore:Algorithms: src/tests/char_encoder_test.cpp File Reference
char_encoder_test.cpp File Reference
#include <boost/thread/thread.hpp>
#include <boost/bind.hpp>
#include <types/Color.hpp>
#include <importers/RawTextImporter.hpp>
#include <encoders/CharMatrixXfEncoder.hpp>
#include <logger/Log.hpp>
#include <logger/ConsoleOutput.hpp>
#include <application/ApplicationState.hpp>
Functions
int main (int argc, char *argv[])
Main program function - tests character importer and encoder.
Function Documentation
int main (int argc, char * argv[])
Main program function - tests character importer and encoder.
Author
tkornuta
Parameters
[in] argc Number of parameters - not used.
[in] argv List of parameters - not used.
Returns
(not used)
Definition at line 48 of file char_encoder_test.cpp.
References mic::types::Batch< DataType, LabelType >::classes(), mic::types::Sample< DataType, LabelType >::data(), mic::types::Batch< DataType, LabelType >::data(), mic::encoders::MatrixSDREncoder< inputDataType, outputDataType >::decodeBatch(), mic::encoders::CharMatrixXfEncoder::decodeSample(), mic::encoders::MatrixSDREncoder< inputDataType, outputDataType >::encodeBatch(), mic::encoders::CharMatrixXfEncoder::encodeSample(), mic::types::Batch< DataType, LabelType >::getNextBatch(), mic::types::Batch< DataType, LabelType >::getRandomSample(), mic::importers::RawTextImporter::importData(), mic::types::Batch< DataType, LabelType >::isLastBatch(), mic::types::Sample< DataType, LabelType >::label(), mic::types::Batch< DataType, LabelType >::setBatchSize(), mic::importers::RawTextImporter::setDataFilename(), and mic::types::Batch< DataType, LabelType >::size().