MachineIntelligenceCore:Algorithms: mic::types::Matrix< T > Class Template Reference
mic::types::Matrix< T > Class Template Reference
Template-typed Matrix of dynamic size. Uses OpenBLAS if found by CMAKE - overloaded, specializations of * operator for types: float, double.
#include <Matrix.hpp>
Public Member Functions
EIGEN_STRONG_INLINE Matrix ()
EIGEN_STRONG_INLINE Matrix (int Rows_, int Cols_)
EIGEN_STRONG_INLINE Matrix (const Eigen::Matrix< T, Eigen::Dynamic, 1 > &vector_)
EIGEN_STRONG_INLINE Matrix (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &matrix_)
EIGEN_STRONG_INLINE Matrix (mic::types::Tensor< T > &tensor_)
EIGEN_STRONG_INLINE
Eigen::Matrix< T,
Eigen::Dynamic, Eigen::Dynamic > & operator= (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &mat_)
EIGEN_STRONG_INLINE
Eigen::Matrix< T,
Eigen::Dynamic, Eigen::Dynamic > operator* (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &mat_)
void setValue (T value_)
void enumerate ()
void randn (T mean=0, T stddev=1)
void rand (T min=0, T max=1)
void elementwiseFunction (T(*func)(T))
void elementwiseFunctionScalar (T(*func)(T, T), T scalar_)
void elementwiseFunctionMatrix (T(*func)(T, T), Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &mat_)
void matrixColumnVectorFunction (T(*func)(T, T), Eigen::Matrix< T, Eigen::Dynamic, 1 > &v_)
void matrixRowVectorFunction (T(*func)(T, T), Eigen::Matrix< T, Eigen::Dynamic, 1 > &v_)
void repeatVector (Eigen::Matrix< T, Eigen::Dynamic, 1 > &in)
Eigen::Matrix< T,
Eigen::Dynamic, 1 > colwiseReturnMaxIndices ()
T calculateCrossEntropy (Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &targets_)
void zeros ()
T & operator[] (int idx)
T operator[] (int idx) const
template<>
Eigen::MatrixXd operator* (const Eigen::MatrixXd &mat_)
template<>
Eigen::MatrixXf operator* (const Eigen::MatrixXf &mat_)
Private Member Functions
template<class Archive >
void save (Archive &ar, const unsigned int version) const
template<class Archive >
void load (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<typename T>
class mic::types::Matrix< T >
Template-typed Matrix of dynamic size. Uses OpenBLAS if found by CMAKE - overloaded, specializations of * operator for types: float, double.
Template Parameters
T Template parameter denoting elementary type of data used (int, float, double etc.)
Date
Mar 7, 2016
Author
tkornuta
Definition at line 64 of file Matrix.hpp.
Constructor & Destructor Documentation
template<typename T> EIGEN_STRONG_INLINE mic::types::Matrix< T >::Matrix () inline
Constructor. Calls default Eigen::MatrixXf constructor.
Definition at line 71 of file Matrix.hpp.
template<typename T> EIGEN_STRONG_INLINE mic::types::Matrix< T >::Matrix (int Rows_, int Cols_) inline
Constructor. Calls default Eigen::MatrixXf constructor.
Parameters
Rows_ Number of rows.
Cols_ Number of columns.
Definition at line 81 of file Matrix.hpp.
template<typename T> EIGEN_STRONG_INLINE mic::types::Matrix< T >::Matrix (const Eigen::Matrix< T, Eigen::Dynamic, 1 > & vector_) inline
Copying constructor on the basis of a vector. Sets dimensions to rows = size(), cols = 1.
Parameters
vector_ Vector
Definition at line 91 of file Matrix.hpp.
template<typename T> EIGEN_STRONG_INLINE mic::types::Matrix< T >::Matrix (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & matrix_) inline
Copying constructor on the basis of another matrix.
Parameters
matrix_ Matrix to be copied.
Definition at line 103 of file Matrix.hpp.
template<typename T> EIGEN_STRONG_INLINE mic::types::Matrix< T >::Matrix (mic::types::Tensor< T > & tensor_) inline
Copying constructor on the basis of a tensor. Copies dimensions and data. Note: tensor must be 2D.
Parameters
tensor_ Tensor
Definition at line 116 of file Matrix.hpp.
References mic::types::Tensor< T >::data(), mic::types::Tensor< T >::dims(), and mic::types::Tensor< T >::size().
Member Function Documentation
template<typename T> T mic::types::Matrix< T >::calculateCrossEntropy (Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & targets_) inline
Calculates the cross entropy as measure of how accurate given matrix (treated as prediction) fits to the desired (target) matrix.
Parameters
targets_ Desired results (targets) in the form of a matrix of answers.
Returns
Definition at line 396 of file Matrix.hpp.
template<typename T> Eigen::Matrix<T, Eigen::Dynamic, 1> mic::types::Matrix< T >::colwiseReturnMaxIndices () inline
Returns a vector of indices indicating maximal elements in consecutive matrix columns (colwise).
Returns
Vector of indices.
Definition at line 366 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::elementwiseFunction (T(*)(T) func) inline
Applies elementwise function to all matrix elements.
Parameters
func Function to be applied.
Definition at line 242 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::elementwiseFunctionMatrix (T(*)(T, T) func, Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & mat_) inline
Applies elementwise function to all matrix elements and uses additional Matrix mat_ data as function parameter.
Parameters
func Function to be applied.
mat_ Matrix passed to function as argument.
Definition at line 276 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::elementwiseFunctionScalar (T(*)(T, T) func, T scalar_) inline
Applies elementwise function to all matrix elements passing scalar as function argument.
Parameters
func Function to be applied.
scalar_ Scalar passed to function as argument.
Definition at line 259 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::enumerate () inline
Enumerates - sets values of elements to their indices.
Definition at line 185 of file Matrix.hpp.
Referenced by TEST().
template<typename T> template<class Archive > void mic::types::Matrix< T >::load (Archive & ar, const unsigned int version) inline private
Serialization load - loads the matrix object to archive.
Parameters
ar Used archive.
version Version of the matrix class.
Definition at line 456 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::matrixColumnVectorFunction (T(*)(T, T) func, Eigen::Matrix< T, Eigen::Dynamic, 1 > & v_) inline
Applies function to all matrix elements and uses additional vector data as function parameter - columnwise.
Parameters
func Used function
v_ Vector passed to function
Definition at line 299 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::matrixRowVectorFunction (T(*)(T, T) func, Eigen::Matrix< T, Eigen::Dynamic, 1 > & v_) inline
Applies function to all matrix elements and uses additional vector data as function parameter - rowwise.
Parameters
func Used function
v_ Vector passed to function
Definition at line 325 of file Matrix.hpp.
template<> Eigen::MatrixXd mic::types::Matrix< double >::operator* (const Eigen::MatrixXd & mat_) inline
Author
tkornuta
Definition at line 40 of file MatrixXdSpecializations.hpp.
template<> Eigen::MatrixXf mic::types::Matrix< float >::operator* (const Eigen::MatrixXf & mat_) inline
Author
tkornuta
Definition at line 43 of file MatrixXfSpecializations.hpp.
template<typename T> EIGEN_STRONG_INLINE Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> mic::types::Matrix< T >::operator* (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & mat_) inline
Overloaded multiplication operator.
Parameters
mat_ Input matrix
Returns
Resulting matrix - multiplication of this and input mat_.
Definition at line 162 of file Matrix.hpp.
template<typename T> EIGEN_STRONG_INLINE Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>& mic::types::Matrix< T >::operator= (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & mat_) inline
Overloaded assignment operator - calls base operator.
Parameters
mat_ Input matrix
Returns
An exact copy of the input matrix.
Definition at line 149 of file Matrix.hpp.
template<typename T> T& mic::types::Matrix< T >::operator[] (int idx) inline
Definition at line 419 of file Matrix.hpp.
template<typename T> T mic::types::Matrix< T >::operator[] (int idx) const inline
Definition at line 423 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::rand (T min = 0, T max = 1) inline
Set values of all matrix elements to random numbers from range <min, max> - uniform distribution.
Parameters
min Min value.
max Max value.
Returns
Random real value.
Definition at line 221 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::randn (T mean = 0, T stddev = 1) inline
Set values of all matrix elements to random with a normal distribution.
Parameters
mean Mean
stddev Variance
Definition at line 199 of file Matrix.hpp.
Referenced by TEST().
template<typename T> void mic::types::Matrix< T >::repeatVector (Eigen::Matrix< T, Eigen::Dynamic, 1 > & in) inline
Sets the consecutive columns to be equal to given vector.
Parameters
in Input vector, that will be "cloned".
Definition at line 352 of file Matrix.hpp.
template<typename T> template<class Archive > void mic::types::Matrix< T >::save (Archive & ar, const unsigned int version) const inline private
Serialization save - saves the matrix object to archive.
Parameters
ar Used archive.
version Version of the matrix class.
Definition at line 438 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::setValue (T value_) inline
Sets values of all element to the value given as parameter.
Parameters
value_ The value to be set.
Definition at line 173 of file Matrix.hpp.
template<typename T> void mic::types::Matrix< T >::zeros () inline
Set zeros.
Definition at line 415 of file Matrix.hpp.
Referenced by TEST().
Friends And Related Function Documentation
template<typename T> friend class boost::serialization::access friend
Definition at line 430 of file Matrix.hpp.
The documentation for this class was generated from the following file:
src/types/Matrix.hpp