MachineIntelligenceCore:Algorithms: src/types/MatrixTests.cpp File Reference
MatrixTests.cpp File Reference
#include <gtest/gtest.h>
#include <fstream>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <types/Matrix.hpp>
Macros
#define private public
Functions
TEST (Matrix, Dimensions2x5)
TEST (Matrix, Serialization)
TEST (Matrix, OperatorAssignmentFloat)
TEST (Matrix, Enumeration2x3)
TEST (Matrix, ArmadilloCompatibilityTest)
int main (int argc, char **argv)
Detailed Description
Copyright (C) tkornuta, IBM Corporation 2015-2019
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
: Tomasz Kornuta tkorn.nosp@m.ut@u.nosp@m.s.ibm.nosp@m..com : Nov 22, 2016
Copyright (c) 2016, IBM Corporation. All rights reserved.
Definition in file MatrixTests.cpp.
Macro Definition Documentation
#define private public
Definition at line 33 of file MatrixTests.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 170 of file MatrixTests.cpp.
TEST (Matrix , Dimensions2x5)
Tests whether matrix has proper dimensions (2x5).
Definition at line 39 of file MatrixTests.cpp.
TEST (Matrix , Serialization)
Tests matrix serialization.
Definition at line 55 of file MatrixTests.cpp.
References mic::types::Matrix< T >::randn().
TEST (Matrix , OperatorAssignmentFloat)
Tests assignment operator.
Definition at line 95 of file MatrixTests.cpp.
TEST (Matrix , Enumeration2x3)
Tests enumeration.
Definition at line 117 of file MatrixTests.cpp.
References mic::types::Matrix< T >::enumerate().
TEST (Matrix , ArmadilloCompatibilityTest)
Tests functions added to make Eigen-derived Matrix as much compatible to Armadillo-derived Matrix as possible.
Definition at line 157 of file MatrixTests.cpp.
References mic::types::Matrix< T >::zeros().