MachineIntelligenceCore:Algorithms: mic::types::NESWAction Class Reference
mic::types::NESWAction Class Reference
Class representing an N/E/S/W action.
#include <Action2D.hpp>
Public Member Functions
NESWAction ()
NESWAction (NESW type_)
NESWAction (size_t type_)
void setAction (NESW type_)
Public Member Functions inherited from mic::types::Action2D< NESW >
virtual ~Action2D ()
NESW getType ()
Public Member Functions inherited from mic::types::Action2DInterface
Action2DInterface ()
Friends
std::ostream & operator<< (std::ostream &os_, const NESWAction &ac_)
Additional Inherited Members
Public Attributes inherited from mic::types::Action2DInterface
int dx
Increment according to x axis.
int dy
Increment according to y axis.
Protected Member Functions inherited from mic::types::Action2D< NESW >
Action2D ()
Protected Attributes inherited from mic::types::Action2D< NESW >
NESW type
Detailed Description
Class representing an N/E/S/W action.
Author
tkornuta
Definition at line 124 of file Action2D.hpp.
Constructor & Destructor Documentation
mic::types::NESWAction::NESWAction () inline
NESW action constructor. Sets action to none.
Definition at line 129 of file Action2D.hpp.
References mic::types::None, and mic::types::Action2D< NESW >::type.
mic::types::NESWAction::NESWAction (NESW type_) inline
Default NESW action constructor. Sets increments according to action type.
Definition at line 134 of file Action2D.hpp.
References setAction().
mic::types::NESWAction::NESWAction (size_t type_) inline
Default NESW action constructor. Sets increments according to action type.
Definition at line 139 of file Action2D.hpp.
References setAction().
Member Function Documentation
void mic::types::NESWAction::setAction (NESW type_) inline virtual
Sets increments according to action value.
Parameters
ActionType Type of action.
Implements mic::types::Action2D< NESW >.
Definition at line 145 of file Action2D.hpp.
References mic::types::Action2DInterface::dx, mic::types::Action2DInterface::dy, mic::types::East, mic::types::Exit, mic::types::None, mic::types::North, mic::types::South, mic::types::Action2D< NESW >::type, and mic::types::West.
Referenced by NESWAction(), and mic::types::RandomNESWAction::RandomNESWAction().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os_, const NESWAction & ac_) friend
Returns ostream containing description of given position.
Parameters
os_ Ostream.
pos_ Position.
Returns
Returned ostream object.
Definition at line 164 of file Action2D.hpp.
The documentation for this class was generated from the following file:
src/types/Action2D.hpp