MachineIntelligenceCore:Algorithms: mic::types::Sample< DataType, LabelType > Class Template Reference
mic::types::Sample< DataType, LabelType > Class Template Reference
Template class storing the data-label pairs. Additionally it stores the the index of the sample (mainly for debug purposes).
#include <Sample.hpp>
Public Member Functions
Sample ()
Sample (std::shared_ptr< DataType > data_, std::shared_ptr< LabelType > label_, size_t index_=-1)
Sample (const mic::types::Sample< DataType, LabelType > &sample_)
mic::types::Sample< DataType,
LabelType > & operator= (const mic::types::Sample< DataType, LabelType > &sample_)
virtual ~Sample ()
std::shared_ptr< DataType > data () const
Returns the sample data.
std::shared_ptr< LabelType > label () const
Returns the returns the sample label.
size_t index () const
Returns the sample number (the sample "position" in original dataset).
Private Attributes
std::shared_ptr< DataType > sample_data
Stores the data.
std::shared_ptr< LabelType > sample_label
Stores the label.
size_t sample_index
The sample index (the sample "position" in original dataset).
Detailed Description
template<typename DataType, typename LabelType>
class mic::types::Sample< DataType, LabelType >
Template class storing the data-label pairs. Additionally it stores the the index of the sample (mainly for debug purposes).
Template Parameters
DataType Template parameter defining the sample data type.
LabelType Template parameters defining the sample label label.
Author
tkornuta
Definition at line 38 of file Sample.hpp.
Constructor & Destructor Documentation
template<typename DataType, typename LabelType> mic::types::Sample< DataType, LabelType >::Sample () inline
Constructor without parameters - nulls both data and label pointers and set index to -1.
Definition at line 44 of file Sample.hpp.
template<typename DataType, typename LabelType> mic::types::Sample< DataType, LabelType >::Sample (std::shared_ptr< DataType > data_, std::shared_ptr< LabelType > label_, size_t index_ = -1) inline
Constructor.
Parameters
data_ The sample itself (data).
label_ Sample label.
index_ Sample index.
Definition at line 52 of file Sample.hpp.
template<typename DataType, typename LabelType> mic::types::Sample< DataType, LabelType >::Sample (const mic::types::Sample< DataType, LabelType > & sample_) inline
Copy constructor.
Parameters
sample_ Sample to be copied.
Definition at line 58 of file Sample.hpp.
template<typename DataType, typename LabelType> virtual mic::types::Sample< DataType, LabelType >::~Sample () inline virtual
Destructor. Empty for now.
Definition at line 77 of file Sample.hpp.
Member Function Documentation
template<typename DataType, typename LabelType> std::shared_ptr<DataType> mic::types::Sample< DataType, LabelType >::data () const inline
Returns the sample data.
Definition at line 80 of file Sample.hpp.
References mic::types::Sample< DataType, LabelType >::sample_data.
Referenced by mic::types::Batch< mic::types::MatrixXf, unsigned int >::add(), and main().
template<typename DataType, typename LabelType> size_t mic::types::Sample< DataType, LabelType >::index () const inline
Returns the sample number (the sample "position" in original dataset).
Definition at line 90 of file Sample.hpp.
References mic::types::Sample< DataType, LabelType >::sample_index.
Referenced by mic::types::Batch< mic::types::MatrixXf, unsigned int >::add().
template<typename DataType, typename LabelType> std::shared_ptr<LabelType> mic::types::Sample< DataType, LabelType >::label () const inline
Returns the returns the sample label.
Definition at line 85 of file Sample.hpp.
References mic::types::Sample< DataType, LabelType >::sample_label.
Referenced by mic::types::Batch< mic::types::MatrixXf, unsigned int >::add(), and main().
template<typename DataType, typename LabelType> mic::types::Sample<DataType, LabelType>& mic::types::Sample< DataType, LabelType >::operator= (const mic::types::Sample< DataType, LabelType > & sample_) inline
Assignment operator - sets pointers and number.
Parameters
sample_ Sample to be copied.
Returns
An exact copy of the input sample.
Definition at line 65 of file Sample.hpp.
References mic::types::Sample< DataType, LabelType >::sample_data, mic::types::Sample< DataType, LabelType >::sample_index, and mic::types::Sample< DataType, LabelType >::sample_label.
Member Data Documentation
template<typename DataType, typename LabelType> std::shared_ptr<DataType> mic::types::Sample< DataType, LabelType >::sample_data private
Stores the data.
Definition at line 96 of file Sample.hpp.
Referenced by mic::types::Sample< DataType, LabelType >::data(), and mic::types::Sample< DataType, LabelType >::operator=().
template<typename DataType, typename LabelType> size_t mic::types::Sample< DataType, LabelType >::sample_index private
The sample index (the sample "position" in original dataset).
Definition at line 102 of file Sample.hpp.
Referenced by mic::types::Sample< DataType, LabelType >::index(), and mic::types::Sample< DataType, LabelType >::operator=().
template<typename DataType, typename LabelType> std::shared_ptr<LabelType> mic::types::Sample< DataType, LabelType >::sample_label private
Stores the label.
Definition at line 99 of file Sample.hpp.
Referenced by mic::types::Sample< DataType, LabelType >::label(), and mic::types::Sample< DataType, LabelType >::operator=().
The documentation for this class was generated from the following file:
src/types/Sample.hpp