MachineIntelligenceCore:Algorithms: src/types/TensorTests.cpp File Reference
TensorTests.cpp File Reference
#include <gtest/gtest.h>
#include <fstream>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <types/Tensor.hpp>
#include <types/Matrix.hpp>
Macros
#define private public
Functions
TEST (Tensor, Dimensions2x5)
TEST (Tensor, Enumeration2x3)
TEST (Tensor, Serialization)
TEST (Tensor, Im2Col2x3)
int main (int argc, char **argv)
Macro Definition Documentation
#define private public
Definition at line 33 of file TensorTests.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 149 of file TensorTests.cpp.
TEST (Tensor , Dimensions2x5)
Tests whether matrix has proper dimensions (2x5).
Definition at line 40 of file TensorTests.cpp.
TEST (Tensor , Enumeration2x3)
Tests enumeration.
Definition at line 57 of file TensorTests.cpp.
References mic::types::Tensor< T >::enumerate().
TEST (Tensor , Serialization)
Tests Tensor serialization.
Definition at line 89 of file TensorTests.cpp.
References mic::types::Tensor< T >::dimensions, mic::types::Tensor< T >::elements, and mic::types::Tensor< T >::randn().
TEST (Tensor , Im2Col2x3)
Tests im2col.
Definition at line 138 of file TensorTests.cpp.
References mic::types::Tensor< T >::enumerate().